local p = premake
local tree = p.tree
local project = p.project
local config = p.config
local creator = p.modules.qtcreator

creator.project = {}
local m = creator.project


function m.generateRun(wks)
	creator.tprint(wks)
	_p(3,'<valuemap type="QVariantMap" key="ProjectExplorer.Target.RunConfiguration.0">')
	_p(4,'<value type="bool" key="Analyzer.QmlProfiler.AggregateTraces">false</value>')
	_p(4,'<value type="bool" key="Analyzer.QmlProfiler.FlushEnabled">false</value>')
	_p(4,'<value type="uint" key="Analyzer.QmlProfiler.FlushInterval">1000</value>')
	_p(4,'<value type="QString" key="Analyzer.QmlProfiler.LastTraceFile"></value>')
	_p(4,'<value type="bool" key="Analyzer.QmlProfiler.Settings.UseGlobalSettings">true</value>')
	_p(4,'<valuelist type="QVariantList" key="Analyzer.Valgrind.AddedSuppressionFiles"/>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.Callgrind.CollectBusEvents">false</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.Callgrind.CollectSystime">false</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.Callgrind.EnableBranchSim">false</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.Callgrind.EnableCacheSim">false</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.Callgrind.EnableEventToolTips">true</value>')
	_p(4,'<value type="double" key="Analyzer.Valgrind.Callgrind.MinimumCostRatio">0.01</value>')
	_p(4,'<value type="double" key="Analyzer.Valgrind.Callgrind.VisualisationMinimumCostRatio">10</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.FilterExternalIssues">true</value>')
	_p(4,'<value type="int" key="Analyzer.Valgrind.LeakCheckOnFinish">1</value>')
	_p(4,'<value type="int" key="Analyzer.Valgrind.NumCallers">25</value>')
	_p(4,'<valuelist type="QVariantList" key="Analyzer.Valgrind.RemovedSuppressionFiles"/>')
	_p(4,'<value type="int" key="Analyzer.Valgrind.SelfModifyingCodeDetection">1</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.Settings.UseGlobalSettings">true</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.ShowReachable">false</value>')
	_p(4,'<value type="bool" key="Analyzer.Valgrind.TrackOrigins">true</value>')
	_p(4,'<value type="QString" key="Analyzer.Valgrind.ValgrindExecutable">valgrind</value>')
	_p(4,'<valuelist type="QVariantList" key="Analyzer.Valgrind.VisibleErrorKinds">')
	_p(5,'<value type="int">0</value>')
	_p(5,'<value type="int">1</value>')
	_p(5,'<value type="int">2</value>')
	_p(5,'<value type="int">3</value>')
	_p(5,'<value type="int">4</value>')
	_p(5,'<value type="int">5</value>')
	_p(5,'<value type="int">6</value>')
	_p(5,'<value type="int">7</value>')
	_p(5,'<value type="int">8</value>')
	_p(5,'<value type="int">9</value>')
	_p(5,'<value type="int">10</value>')
	_p(5,'<value type="int">11</value>')
	_p(5,'<value type="int">12</value>')
	_p(5,'<value type="int">13</value>')
	_p(5,'<value type="int">14</value>')
	_p(4,'</valuelist>')
	_p(4,'<value type="int" key="PE.EnvironmentAspect.Base">2</value>')
	_p(4,'<valuelist type="QVariantList" key="PE.EnvironmentAspect.Changes"/>')
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">%s</value>',wks.name)
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">Qt4ProjectManager.Qt4RunConfiguration:%s.pro</value>',path.join(wks.location,wks.filename))
	_p(4,'<value type="bool" key="QmakeProjectManager.QmakeRunConfiguration.UseLibrarySearchPath">true</value>')
	_p(4,'<value type="QString" key="Qt4ProjectManager.Qt4RunConfiguration.CommandLineArguments"></value>')
	_p(4,'<value type="QString" key="Qt4ProjectManager.Qt4RunConfiguration.ProFile">%s.pro</value>',wks.filename)
	_p(4,'<value type="bool" key="Qt4ProjectManager.Qt4RunConfiguration.UseDyldImageSuffix">false</value>')
	_p(4,'<value type="bool" key="Qt4ProjectManager.Qt4RunConfiguration.UseTerminal">false</value>')
	_p(4,'<value type="QString" key="Qt4ProjectManager.Qt4RunConfiguration.UserWorkingDirectory"></value>')
	_p(4,'<value type="QString" key="Qt4ProjectManager.Qt4RunConfiguration.UserWorkingDirectory.default">%s</value>',wks.basedir)
	_p(4,'<value type="uint" key="RunConfiguration.QmlDebugServerPort">3768</value>')
	_p(4,'<value type="bool" key="RunConfiguration.UseCppDebugger">false</value>')
	_p(4,'<value type="bool" key="RunConfiguration.UseCppDebuggerAuto">true</value>')
	_p(4,'<value type="bool" key="RunConfiguration.UseMultiProcess">false</value>')
	_p(4,'<value type="bool" key="RunConfiguration.UseQmlDebugger">false</value>')
	_p(4,'<value type="bool" key="RunConfiguration.UseQmlDebuggerAuto">true</value>')
	_p(3,'</valuemap>')
	_p(3,'<value type="int" key="ProjectExplorer.Target.RunConfigurationCount">1</value>')
end

-- Project: Generate the cmake project file.
function m.generateBuild(prj, cfg, index)
	_p(3,'<valuemap type="QVariantMap" key="ProjectExplorer.Target.BuildConfiguration.%d">',index)
	_p(4,'<value type="QString" key="ProjectExplorer.BuildConfiguration.BuildDirectory">%s</value>',cfg.location)
	_p(4,'<valuemap type="QVariantMap" key="ProjectExplorer.BuildConfiguration.BuildStepList.0">')
	_p(5,'<valuemap type="QVariantMap" key="ProjectExplorer.BuildStepList.Step.0">')
	_p(6,'<value type="bool" key="ProjectExplorer.BuildStep.Enabled">true</value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">qmake</value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">QtProjectManager.QMakeBuildStep</value>')
	_p(6,'<value type="bool" key="QtProjectManager.QMakeBuildStep.LinkQmlDebuggingLibrary">true</value>')
	_p(6,'<value type="QString" key="QtProjectManager.QMakeBuildStep.QMakeArguments">CONFIG+=%s</value>',creator.targetname(cfg))
	_p(6,'<value type="bool" key="QtProjectManager.QMakeBuildStep.QMakeForced">false</value>')
	_p(6,'<value type="bool" key="QtProjectManager.QMakeBuildStep.SeparateDebugInfo">false</value>')
	_p(6,'<value type="bool" key="QtProjectManager.QMakeBuildStep.UseQtQuickCompiler">false</value>')
	_p(5,'</valuemap>')
	_p(5,'<valuemap type="QVariantMap" key="ProjectExplorer.BuildStepList.Step.1">')
	_p(6,'<value type="bool" key="ProjectExplorer.BuildStep.Enabled">true</value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Make</value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">Qt4ProjectManager.MakeStep</value>')
	_p(6,'<valuelist type="QVariantList" key="Qt4ProjectManager.MakeStep.AutomaticallyAddedMakeArguments">')
	_p(7,'<value type="QString">-w</value>')
	_p(7,'<value type="QString">-r</value>')
	_p(6,'</valuelist>')
	_p(6,'<value type="bool" key="Qt4ProjectManager.MakeStep.Clean">false</value>')
	_p(6,'<value type="QString" key="Qt4ProjectManager.MakeStep.MakeArguments"></value>')
	_p(6,'<value type="QString" key="Qt4ProjectManager.MakeStep.MakeCommand"></value>')
	_p(5,'</valuemap>')
	_p(5,'<value type="int" key="ProjectExplorer.BuildStepList.StepsCount">2</value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Build</value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">ProjectExplorer.BuildSteps.Build</value>')
	_p(4,'</valuemap>')
	_p(4,'<valuemap type="QVariantMap" key="ProjectExplorer.BuildConfiguration.BuildStepList.1">')
	_p(5,'<valuemap type="QVariantMap" key="ProjectExplorer.BuildStepList.Step.0">')
	_p(6,'<value type="bool" key="ProjectExplorer.BuildStep.Enabled">true</value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Make</value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(6,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">Qt4ProjectManager.MakeStep</value>')
	_p(6,'<valuelist type="QVariantList" key="Qt4ProjectManager.MakeStep.AutomaticallyAddedMakeArguments">')
	_p(7,'<value type="QString">-w</value>')
	_p(7,'<value type="QString">-r</value>')
	_p(6,'</valuelist>')
	_p(6,'<value type="bool" key="Qt4ProjectManager.MakeStep.Clean">true</value>')
	_p(6,'<value type="QString" key="Qt4ProjectManager.MakeStep.MakeArguments">clean</value>')
	_p(6,'<value type="QString" key="Qt4ProjectManager.MakeStep.MakeCommand"></value>')
	_p(5,'</valuemap>')
	_p(5,'<value type="int" key="ProjectExplorer.BuildStepList.StepsCount">1</value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Clean</value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">ProjectExplorer.BuildSteps.Clean</value>')
	_p(4,'</valuemap>')
	_p(4,'<value type="int" key="ProjectExplorer.BuildConfiguration.BuildStepListCount">2</value>')
	_p(4,'<value type="bool" key="ProjectExplorer.BuildConfiguration.ClearSystemEnvironment">false</value>')
	_p(4,'<valuelist type="QVariantList" key="ProjectExplorer.BuildConfiguration.UserEnvironmentChanges"/>')
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">%s</value>',creator.targetname(cfg))
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName">%s</value>',creator.targetname(cfg))
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">Qt4ProjectManager.Qt4BuildConfiguration</value>')
	_p(4,'<value type="int" key="Qt4ProjectManager.Qt4BuildConfiguration.BuildConfiguration">2</value>')
	_p(4,'<value type="bool" key="Qt4ProjectManager.Qt4BuildConfiguration.UseShadowBuild">true</value>')
	_p(3,'</valuemap>')
end

return m
