local p = premake
local project = p.project
local workspace = p.workspace
local tree = p.tree
local creator = p.modules.qtcreator
local config = require("configuration")
creator.project = require("project")
local pycontent = require('template')

creator.workspace = {}
local m = creator.workspace

function iterateWorkspace(wks, handle)
	local tr = workspace.grouptree(wks)
	local index = 0
	tree.traverse(tr, {
		onleaf = function(n)
			local prj = n.project
			for cfg in project.eachconfig(prj) do
				handle(prj, cfg, index)
				index = index + 1;
			end
		end,
		onbranch = function(n)
		end,
	})

	return index
end

function m.generateQmake(wks)
	-- p.utf8()
	-- _p('')
	_p('# Generated by Premake %s', p._VERSION)
	_p('')
	iterateWorkspace(wks, config.generate)
end

-- Generate a cmake workspace
function m.generateUser(wks)
	_p('<?xml version="1.0" encoding="UTF-8"?>')
	_p('<!DOCTYPE QtCreatorProject>')
	_p('<!-- Written by Premake %s -->', p._VERSION)
	_p('<qtcreator>')

	_p(1,'<data>')
	_p(2,'<variable>EnvironmentId</variable>')
	_p(2,'<value type="QByteArray">{__UUID01__}</value>')
	_p(1,'</data>')

	_p(1,'<data>')
	_p(2,'<variable>ProjectExplorer.Project.Target.0</variable>')
	_p(2,'<valuemap type="QVariantMap">')
	_p(3,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Desktop</value>')
	_p(3,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName">Desktop</value>')
	_p(3,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">{__UUID02__}</value>')
	_p(3,'<value type="int" key="ProjectExplorer.Target.ActiveBuildConfiguration">0</value>')
	_p(3,'<value type="int" key="ProjectExplorer.Target.ActiveDeployConfiguration">0</value>')
	_p(3,'<value type="int" key="ProjectExplorer.Target.ActiveRunConfiguration">0</value>')


	local cfgCount = iterateWorkspace(wks, creator.project.generateBuild)
	_p(3,'<value type="int" key="ProjectExplorer.Target.BuildConfigurationCount">%d</value>',cfgCount)

	_p(3,'<valuemap type="QVariantMap" key="ProjectExplorer.Target.DeployConfiguration.0">')
	_p(4,'<valuemap type="QVariantMap" key="ProjectExplorer.BuildConfiguration.BuildStepList.0">')
	_p(5,'<value type="int" key="ProjectExplorer.BuildStepList.StepsCount">0</value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Deploy</value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(5,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">ProjectExplorer.BuildSteps.Deploy</value>')
	_p(4,'</valuemap>')
	_p(4,'<value type="int" key="ProjectExplorer.BuildConfiguration.BuildStepListCount">1</value>')
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DefaultDisplayName">Local Deploy</value>')
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.DisplayName"></value>')
	_p(4,'<value type="QString" key="ProjectExplorer.ProjectConfiguration.Id">ProjectExplorer.DefaultDeployConfiguration</value>')
	_p(3,'</valuemap>')
	_p(3,'<value type="int" key="ProjectExplorer.Target.DeployConfigurationCount">1</value>')

	_p(3,'<valuemap type="QVariantMap" key="ProjectExplorer.Target.PluginSettings"/>')

	creator.project.generateRun(wks)

	_p(2,'</valuemap>')
	_p(1,'</data>')

	_p(1,'<data>')
	_p(2,'<variable>ProjectExplorer.Project.TargetCount</variable>')
	_p(2,'<value type="int">1</value>')
	_p(1,'</data>')

	_p(1,'<data>')
	_p(2,'<variable>ProjectExplorer.Project.Updater.FileVersion</variable>')
	_p(2,'<value type="int">18</value>')
	_p(1,'</data>')
	_p('</qtcreator>')
	_p('')
end

function m.generateTemplate(wks)
	_p(pycontent)
end
